
def print_statement(club, average_expected_putts, green_hit_count, SIMULATION_RUNS, chip_count, chip_green_count,chip_miss_count,average_expected_strokes):
    print()
    print("========== SIMULATION RESULTS ==========")
    print()
    print("Club:", club)
    print("Green hits:",green_hit_count,"/",SIMULATION_RUNS)
    print("Green hit percentage:", (green_hit_count / SIMULATION_RUNS) * 100, "%")
    print()
    print("Shots requiring a chip:", chip_count)
    print("Chips that hit the green:", chip_green_count)
    print("Chip success percentage:",(chip_green_count / chip_count * 100 if chip_count > 0 else 0),"%")
    print()
    print("Chips that missed the green:",chip_miss_count)
    print()
    print("Average expected strokes:",average_expected_strokes)
    print("Average putts after reaching green:",average_expected_putts)
    print()

def print_optimization_results(best_result):
    print()
    print()
    print("========================================")
    print("          OPTIMAL SHOT STRATEGY")
    print("========================================")
    print()

    print("Club:", best_result["club"])
    print("Swing:", f'{best_result["swing_percentage"]:.0f}%')
    print("Aim:", f'{best_result["aim"]:+.1f} yards')
    print("Expected strokes", f'{best_result["expected_strokes"]:.3f}')
    print("Expected putts:", f'{best_result["expected_putts"]:.3f}')
    print("Green hit percentage:" f'{best_result["green_hit_percentage"]:.1f}%')
    print("Chip success percentage:", f'{best_result["chip_success_percentage"]:.1f}%')
    print()